sudo: requiered
services:
  - docker

before_install:
  - docker build -t maulima89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maulima89/docker-react npm run test -- --coverage

